#count the number of vowels and consonants

text = str(input("Write your sentence and I will count vowels and consonants: "))

a = text.count("a")
b = text.count("b")
c = text.count("c")
d = text.count("d")
e = text.count("e")
f = text.count("f")
g = text.count("g")
h = text.count("h")
i = text.count("i")
j = text.count("j")
k = text.count("k")
l = text.count("l")
m = text.count("m")
n = text.count("n")
o = text.count("o")
p = text.count("p")
q = text.count("q")
r = text.count("r")
s = text.count("s")
t = text.count("t")
u = text.count("u")
v = text.count("v")
w = text.count("w")
x = text.count("x")
y = text.count("y")
z = text.count("z")

a1 = text.count("A")
b1 = text.count("B")
c1 = text.count("C")
d1 = text.count("D")
e1 = text.count("E")
f1 = text.count("F")
g1 = text.count("G")
h1 = text.count("H")
i1 = text.count("I")
j1 = text.count("J")
k1 = text.count("K")
l1 = text.count("L")
m1 = text.count("M")
n1 = text.count("N")
o1 = text.count("O")
p1 = text.count("P")
q1 = text.count("Q")
r1 = text.count("E")
s1 = text.count("S")
t1 = text.count("T")
u1 = text.count("U")
v1 = text.count("V")
w1 = text.count("W")
x1 = text.count("X")
y1 = text.count("Y")
z1 = text.count("Z")

print("In your sentence there are: ", a+a1+o+o1+e+e1+i+i1+u+u1, " Vowels")
print("In your sentence there are: ", b+b1+c+c1+d+d1+f+f1+g+g1+h+h1+j+j1+k+k1+l+l1+m+m1+n+n1+p+p1+q+q1+r+r1+s+s1+t+t1+v+v1+w+w1+x+x1+y+y1+z+z1, " Consonants")